In [1]:
import pandas as pd
import numpy as np

import sys
sys.path.append('../../')

print('HW3 Practice Problem (4)')

from Perceptron.Perceptrons import StandardPerceptron

HW3 Practice Problem (4)


In [2]:
def encode_binary(number, num_bits):
    binary_representation = format(number, f"0{num_bits}b")
    binary_list = [bit == '1' for bit in binary_representation]
    return binary_list

In [3]:

def function(x):
    half_point = len(x)//2
    return np.any(x[:half_point]) or np.any(np.bitwise_not(x[half_point:]))

def generate_datapoints(n):
    assert n%2==0, 'n must be even'
    k = n//2
    
    datapoints = []
    
    for i in range(0, 2**n):
        x = encode_binary(i, n)
        y = function(x)
        datapoints.append(np.concatenate([x, [y]]))
    
    return np.array(datapoints)

data = generate_datapoints(6)

In [12]:
data[0:1,:-1]

array([[False, False, False, False, False, False]])

In [5]:
def map_labels(yTF):
    lookup = {True:1, False:-1}
    return np.array([ lookup[k] for k in yTF ])

p = StandardPerceptron(
    data=data[0:1,:-1], # slice the data to only have one example so we have 1 iteration
    labels=map_labels(data[0:1,-1]),
    r=0.0001,
    T=1
)

In [9]:
p.w

array([0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.0001])

In [6]:
y_prime = p.predict(data)

In [7]:
y_prime

array([1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
map_labels(data[:,-1])

array([ 1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])